name: Publish To GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          # prefer breaking at an arbitrary point over outdated mdBook
          mdbook-version: 'latest'
      - run: mdbook build
      - name: Clone pieter-bos.github.io
        uses: actions/checkout@v3
        with:
          repository: pieter-bos/pieter-bos.github.io
          path: pieter-bos.github.io
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - run: |
          cd pieter-bos.github.io
          rm -r vercors-doc || true
          mv ../vercors-doc .
          git config --global user.name "Pieter Bot"
          git config --global user.email "ghpages@pieterbos.me"
          git add .
          git status
          git commit -m 'Update vercors-doc'
          git push